/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.airlino;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;

import android.app.Activity;
import android.content.Context;
import android.net.nsd.NsdManager;
import android.net.nsd.NsdServiceInfo;

@Kroll.module(name = "Airlino", id = "de.appwerft.airlino")
public class AirlinoModule extends KrollModule {
	private static final String LCAT = "AirLino 😈";
	Context ctx;
	NsdManager nsdManager;
	private KrollFunction onSuccessCallback = null;
	private KrollFunction onErrorCallback = null;
	private KrollFunction onResultCallback = null;
	private boolean isPingActive = false;
	private boolean wasPingSuccessful = false;
	String DNSTYPE = "_dockset._tcp.";
	int scanTimeout = 2000;
	int pingTimeout = 1000;
	AirlinoDevices aDevices = new AirlinoDevices();
	@Kroll.constant
	public final int PLAY = 0;
	@Kroll.constant
	public final int STOP = 1;
	public NsdManager.ResolveListener resolveListener;
	public NsdManager.DiscoveryListener discListener = null;

	public AirlinoModule() {
		super();
		resolveListener = new NsdManager.ResolveListener() {
			@Override
			public void onResolveFailed(NsdServiceInfo serviceInfo,
					int errorCode) {
				// Called when the resolve fails. Use the error
				// code to debug.
				Log.e(LCAT, "Resolve failed" + errorCode);
			}

			@Override
			public void onServiceResolved(NsdServiceInfo serviceInfo) {
				Log.d(LCAT, "Resolve succeeded. " + serviceInfo);

				if (isPingActive) {
					wasPingSuccessful = true;
					KrollDict result = new KrollDict();
					result.put("result", true);
					isPingActive = false;
					stopDiscoveryListener();
					Log.d(LCAT, "stopDiscoveryListener()");
					if (onResultCallback != null)
						onResultCallback.call(getKrollObject(), result);
				} else {
					aDevices.add(AirlinoDevice.parseNsdServiceInfo(serviceInfo));
					if (onSuccessCallback != null) {
						onSuccessCallback.call(getKrollObject(),
								aDevices.getAllDevices());
					}
				}
			}
		};
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
	}

	// https://github.com/appcelerator-modules/ti.moddevguide/blob/master/android/src/ti/moddevguide/ModdevguideModule.java
	@Override
	public void onPause(Activity a) {
		tearDown();
		super.onPause(a);

	}

	@Override
	public void onResume(Activity a) {
		super.onResume(a);
		Log.d(LCAT, "onResume");
		this.initializeDiscoveryListener();
	}

	private void tearDown() {
		if (discListener != null)
			nsdManager.stopServiceDiscovery(discListener);
	}

	public void onDestroy(Activity a) {
		tearDown();
		super.onDestroy(a);
	}

	@Kroll.method
	public void isAvailable(KrollDict opt) {
		Object callback;
		wasPingSuccessful = false;
		if (opt.containsKeyAndNotNull("onResult")) {
			callback = opt.get("onResult");
			if (callback instanceof KrollFunction) {
				onResultCallback = (KrollFunction) callback;
			} else
				Log.w(LCAT, "onSuccessFn missed");
		} else
			Log.w(LCAT, "onSuccess missed");
		if (opt.containsKeyAndNotNull("timeout")) {
			scanTimeout = opt.getInt("timeout");
		}
		isPingActive = true;
		this.initializeDiscoveryListener();
	}

	@Kroll.method
	public void startScan(KrollDict opt) {
		Object callback;
		if (opt.containsKeyAndNotNull("onSuccess")) {
			callback = opt.get("onSuccess");
			if (callback instanceof KrollFunction) {
				onSuccessCallback = (KrollFunction) callback;
			} else
				Log.w(LCAT, "onSuccessFn missed");
		} else
			Log.w(LCAT, "onSuccess missed");
		if (opt.containsKeyAndNotNull("onError")) {
			callback = opt.get("onFound");
			if (callback instanceof KrollFunction) {
				onErrorCallback = (KrollFunction) callback;
			}
		}
		if (opt.containsKeyAndNotNull("timeout")) {
			scanTimeout = opt.getInt("timeout");
		}
		this.initializeDiscoveryListener();

	}

	private void stopDiscoveryListener() {
		try {
			nsdManager.stopServiceDiscovery(discListener);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void initializeDiscoveryListener() {
		ctx = TiApplication.getInstance().getApplicationContext();
		nsdManager = (NsdManager) ctx.getSystemService(Context.NSD_SERVICE);
		discListener = new NsdManager.DiscoveryListener() {
			@Override
			public void onDiscoveryStarted(String regType) {
				Log.d(LCAT, "Service discovery started");

			}

			/* a new device is found */
			@Override
			public void onServiceFound(NsdServiceInfo service) {
				nsdManager.resolveService(service, resolveListener);
			}

			/* a device is lost */
			@Override
			public void onServiceLost(NsdServiceInfo service) {
			}

			@Override
			public void onDiscoveryStopped(String serviceType) {
				Log.i(LCAT, "Discovery stopped: " + serviceType);
			}

			@Override
			public void onStartDiscoveryFailed(String serviceType, int errorCode) {
				Log.e(LCAT, "Discovery failed: Error code:" + errorCode);
				nsdManager.stopServiceDiscovery(this);
			}

			@Override
			public void onStopDiscoveryFailed(String serviceType, int errorCode) {
				Log.e(LCAT, "Discovery failed: Error code:" + errorCode);
				nsdManager.stopServiceDiscovery(this);
			}
		};

		nsdManager.discoverServices(DNSTYPE, NsdManager.PROTOCOL_DNS_SD,
				discListener);

		new android.os.Handler().postDelayed(new Runnable() {
			public void run() {
				if (isPingActive && wasPingSuccessful == false) {
					stopDiscoveryListener();
					if (onResultCallback != null) {
						KrollDict result = new KrollDict();
						result.put("result", false);
						onResultCallback.call(getKrollObject(), result);
					}
					isPingActive = false;
				}
			}
		}, (isPingActive) ? pingTimeout : scanTimeout);
	}

}
